export default function AboutPage() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'ui-sans-serif, system-ui' }}>
      <h1>About</h1>
      <p>Generated by create-fict.</p>
    </main>
  )
}
